export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
export const ADD_CART_REQUEST="ADD_CART_REQUEST";
export const ADD_CART_SUCCESS="ADD_CART_SUCCESS";
export const ADD_CART_FAILURE="ADD_CART_FAILURE";
